# Настройки сайта
title: "Такси «Успех» — Белоусовка"
email: taxi.uspeh@example.com
description: "Официальный сайт Такси «Успех» в посёлке Белоусовка. Быстрый заказ, доставка и локальные новости."

# Тема
# Используем стандартную тему GitHub Pages
theme: minima

# Настройки для отображения
minima:
  date_format: "%d.%m.%Y"

# Ваша ветка для публикации
source: .
destination: ./_site

# Исключения (файлы, которые Jekyll должен игнорировать)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
